### ISSUE TITLE
The Download Button Will Not Work On New Phones

### ISSUE THREAD

**Issue by bradenboothby** [PSNAppz/YouTubeMp3Downloader#1]
**Describe the bug**
The download button will not work on new device like the Galaxy s9. The links from YouTube will not paste either

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PSNAppz** [comment]
@bradenboothby Do you have a fix for that?

**Comment by bradenboothby** [comment]
no. i was hoping you do. i try to open it on a galaxy s9, and the download button is unresponsive. it does nothing

**Comment by PSNAppz** [comment]
@bradenboothby Ok Thank you for letting us know about it. We'll fix it soon.

**Comment by bradenboothby** [comment]
yep. i hope you can fix it in a couple days 🙂

**Comment by PSNAppz** [comment]
@bradenbbthby If the problem is from the library that we are using, then in that case it might take longer otherwise we will fix it in a couple of days.

**Comment by bradenboothby** [comment]
okay. i viewed the log and it says that it is registering the click, but nothing is happening.

**Comment by PSNAppz** [comment]
@bradenboothby Thanks for the info.

**Comment by bradenboothby** [comment]
@PSNAppz yep

**Comment by bradenboothby** [comment]
do have any idea on what may be causing this? (so i can help find the issue)

**Comment by PSNAppz** [comment]
@bradenboothby I think it could be the layout file. My exams are going on so probably I will fix it this weekend.

**Comment by bradenboothby** [comment]
do you think it could be how the button is set up?

**Comment by PSNAppz** [comment]
Its also possible.

**Comment by PSNAppz** [comment]
@bradenboothby A fix is coming. Thanks for the issue btw

**Comment by PSNAppz** [comment]
@bradenboothby Let me know if its working for you.
